# Generated by Django 4.2.26 on 2025-11-28 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, help_text='LLM model used to generate this message (e.g., gpt-4, claude-3, llama-3)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_team_shared',
            field=models.BooleanField(default=False, help_text='If True, all team members can access this conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members who can access this conversation', related_name='shared_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='scope',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('team-global', 'Team Global')], default='conversation', help_text='Memory scope: conversation-specific or team-global', max_length=20),
        ),
        migrations.AlterField(
            model_name='memory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata (model_used, importance, etc.)'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['scope', '-created_at'], name='api_memory_scope_7deacc_idx'),
        ),
    ]
