# Generated by Django 4.2.26 on 2025-12-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workspaceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='model_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('deepseek', 'DeepSeek'), ('groq', 'Groq')], max_length=20),
        ),
    ]
